version: "3.9"

services:
  app:
    image: banking-demo:1.0.0
    container_name: demo-transaction-banking
    command: uv run fastapi dev app/main.py --host 0.0.0.0 --port 8919 --reload
    volumes:
      - .:/app
      - ${HOME}/.azure:/root/.azure
    ports:
      - "8919:8919"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: aiops-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    networks:
      - elk_net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.3
    container_name: aiops-logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.monitoring.enabled=true
      - ELASTICSEARCH_HOST=http://aiops-elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=LodplW_EZCRBo1E+f0tl
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    restart: unless-stopped
    networks:
      - elk_net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: aiops-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://aiops-elasticsearch:9200
      - ELASTICSEARCH_SERVICE_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL3Rva2VuX2Z1WFlmSm9CdkdWa3N5eGVDMkFGOlpuSTN3VzdpU21ldmtoNFlyMnB1M2c
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped
    networks:
      - elk_net

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.3
    container_name: filebeat
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    restart: unless-stopped

volumes:
  es_data:
    driver: local

networks:
  elk_net:
    driver: bridge