xpack.encryptedSavedObjects.encryptionKey: "G7h3kL9sP0vN8xZ2fQwRm6tB4yJ1dUcA"
xpack.security.encryptionKey: "D8fT1vK9mQ3pX6sR0bW2yL4nZ7jH5aGq"
xpack.reporting.encryptionKey: "P0kL6nR3sV9wX2bQ7yZ1dF8hT4mC5jAq"
elasticsearch.hosts: ["http://aiops-elasticsearch:9200"]
elasticsearch.username: "kibana_system"
elasticsearch.password: "bpn570YFbsSznSem2M3t"